jobs:
build:
docker:
- image: circleci/python:2.7.16
steps:
- run: sudo pip install jupyter_client
- run: sudo pip install nbconvert
- run: sudo pip install numpy
- run: sudo pip install matplotlib
- run: sudo pip install sklearn
- run: sudo python2 -m pip install ipykernel
- run: sudo python2 -m ipykernel install --user
- run: jupyter-nbconvert --execute ./Notebook.ipynb
- store_artifacts:
path: ./Notebook.html